name: Mastermind

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Generate guesses (10 identical guesses)
        run: |
          python random.py
          echo "---- guesses.txt ----"
          cat guesses.txt

      - name: Run main.py non-interactively (1=single player, 3=easy)
        run: |
          set -euo pipefail
          {
            echo "1"   # mode: single player
            echo "3"   # difficulty
            cat guesses.txt
          } | python main.py | tee game_run.txt

      - name: Upload game transcript
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: mastermind-game-run
          path: game_run.txt

