name: Mastermind

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
      - name: Generate guesses (10 identical guesses)
        run: |
          python .github/workflows/random.py
          echo "---- guesses.txt ----"
          cat guesses.txt

      - name: Run main4.py non-interactively (1=single player, 4=Normal)
        run: |
          set -euo pipefail
          {
            echo "1"     # mode: single player
            echo "4"     # difficulty (level=4)
            cat guesses.txt
            printf 'm\n' # leave single-player session
            printf 'q\n' # quit at main menu
          } | timeout 30s python main3.py | tee game_run.txt

      - name: Upload game transcript
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: mastermind-game-run
          path: game_run.txt

